apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-demo
  namespace: demo
spec:
  provider: azure
  secretObjects:
  - secretName: appinsights-secret
    type: Opaque
    data:
    - objectName: appi-instrumentation-key
      key: ikey
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "demoaks-kv-9nzHtN"
    objects: |
      array:
        - |
          objectName: appi-instrumentation-key
          objectType: secret
    tenantId: "208f9d78-1d29-4742-b3a1-2bf5b887f5e0"