name: CI/CD AKS Microservices

on:
  push:
    branches:
      - master
  pull_request:

env:
  ACR_NAME: demoaksacr9nzhtn
  AKS_RESOURCE_GROUP: demoaks-rg
  AKS_CLUSTER_NAME: demoaks-aks
  K8S_NAMESPACE: demo

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Gateway image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/gateway:latest ./services/gateway
          docker push ${{ env.ACR_NAME }}.azurecr.io/gateway:latest

      - name: Build & Push User Service image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/user:latest ./services/user
          docker push ${{ env.ACR_NAME }}.azurecr.io/user:latest

      - name: Build & Push Order Service image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/order:latest ./services/order
          docker push ${{ env.ACR_NAME }}.azurecr.io/order:latest

  deploy-to-aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} \
                                 --name ${{ env.AKS_CLUSTER_NAME }} \
                                 --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/user-deployment.yaml -n ${{ env.K8S_NAMESPACE }}
          kubectl apply -f k8s/order-deployment.yaml -n ${{ env.K8S_NAMESPACE }}
          kubectl apply -f k8s/gateway-deployment.yaml -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout restart deployment api-gateway -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout restart deployment user-service -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout restart deployment order-service -n ${{ env.K8S_NAMESPACE }}

      - name: Verify deployment
        run: |
          kubectl get po -n ${{ env.K8S_NAMESPACE }}
          kubectl get svc -n ${{ env.K8S_NAMESPACE }}

